// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc_V3n6JFJ5o0k0LhtYK7LOVYKUGFhDmU',
    appId: '1:245208639230:web:a4ead90c861775049967af',
    messagingSenderId: '245208639230',
    projectId: 'movie-app-93c44',
    authDomain: 'movie-app-93c44.firebaseapp.com',
    storageBucket: 'movie-app-93c44.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgFfWDTfbA2UXbkPViq28IWjPa9BGvB5g',
    appId: '1:245208639230:android:0cd97556fee440ef9967af',
    messagingSenderId: '245208639230',
    projectId: 'movie-app-93c44',
    storageBucket: 'movie-app-93c44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUFJCm317f_UHSV3IOlqQdCfce2fpP75k',
    appId: '1:245208639230:ios:a02f8537fe4091aa9967af',
    messagingSenderId: '245208639230',
    projectId: 'movie-app-93c44',
    storageBucket: 'movie-app-93c44.appspot.com',
    iosBundleId: 'com.example.movie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUFJCm317f_UHSV3IOlqQdCfce2fpP75k',
    appId: '1:245208639230:ios:a02f8537fe4091aa9967af',
    messagingSenderId: '245208639230',
    projectId: 'movie-app-93c44',
    storageBucket: 'movie-app-93c44.appspot.com',
    iosBundleId: 'com.example.movie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc_V3n6JFJ5o0k0LhtYK7LOVYKUGFhDmU',
    appId: '1:245208639230:web:da4f2cae8ca187519967af',
    messagingSenderId: '245208639230',
    projectId: 'movie-app-93c44',
    authDomain: 'movie-app-93c44.firebaseapp.com',
    storageBucket: 'movie-app-93c44.appspot.com',
  );
}
